# Generated by Django 4.1.7 on 2023-08-08 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0002_rename_employeesid_employees_employeeid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='PhotoFieldName',
        ),
    ]
